Exception in thread Thread-4:
Traceback (most recent call last):
  File "D:\Program Files\Python26\lib\threading.py", line 525, in __bootstrap_inner
    self.run()
  File "D:\Projets\Py Projects\Jsocket\server\client.py", line 41, in run
    data = self.client_socket.recv(1024).strip()
error: [Errno 10054] Une connexion existante a dû être fermée par l'hôte distant

Exception in thread Thread-5:
Traceback (most recent call last):
  File "D:\Program Files\Python26\lib\threading.py", line 525, in __bootstrap_inner
    self.run()
  File "D:\Projets\Py Projects\Jsocket\server\client.py", line 41, in run
    data = self.client_socket.recv(1024).strip()
error: [Errno 10054] Une connexion existante a dû être fermée par l'hôte distant

Exception in thread Thread-6:
Traceback (most recent call last):
  File "D:\Program Files\Python26\lib\threading.py", line 525, in __bootstrap_inner
    self.run()
  File "D:\Projets\Py Projects\Jsocket\server\client.py", line 41, in run
    data = self.client_socket.recv(1024).strip()
error: [Errno 10054] Une connexion existante a dû être fermée par l'hôte distant

Exception in thread Thread-7:
Traceback (most recent call last):
  File "D:\Program Files\Python26\lib\threading.py", line 525, in __bootstrap_inner
    self.run()
  File "D:\Projets\Py Projects\Jsocket\server\client.py", line 41, in run
    data = self.client_socket.recv(1024).strip()
error: [Errno 10054] Une connexion existante a dû être fermée par l'hôte distant

Exception in thread Thread-8:
Traceback (most recent call last):
  File "D:\Program Files\Python26\lib\threading.py", line 525, in __bootstrap_inner
    self.run()
  File "D:\Projets\Py Projects\Jsocket\server\client.py", line 41, in run
    data = self.client_socket.recv(1024).strip()
error: [Errno 10054] Une connexion existante a dû être fermée par l'hôte distant

